version: '3.8'

services:
  bot:
    image: ://mcr.microsoft.com
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    working_dir: /workspace
    user: vscode 

  admin_api:
    image: ://mcr.microsoft.com
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace

